### ISSUE TITLE
WSL flag no longer exists

### ISSUE THREAD

**Issue by HandleTBC** [XFY9326/Zotero-WSL-ProxyServer#1]
Hi there,

Thanks so much for making this, perfectly solved my problem.

However, one fault. WSL has dropped `--version`. So the command which checks for WSL's existence returns an error code. I changed mine to `wsl --status` and it went through A-OK.

Thanks again.

**Comment by XFY9326** [comment]
Thanks for your feedback, this issue has been fixed in version 0.1.0.3.
