### ISSUE TITLE
It also works for LaTeX devcontainer!

### ISSUE THREAD

**Issue by wohenbushuang** [XFY9326/Zotero-WSL-ProxyServer#3]
Greetings, and thanks for this useful tool!

I would like to share my experience. I use devcontainer for LaTeX compilation instead of installing LaTeX in WSL, so I can easily switch to different configurations (e.g., old versions for old LaTeX project) and don't need to reinstall LaTeX when I re-init my WSL. Just pull the specific docker image I need. I also used to be suffered from the Zotero connection problem, then I luckily found this tool. After tests, I found that this tool also works for the devcontainer. The only difference is that, you have to use the IP address shown in `Serving on` line not `[Windows name in WSL].local` for extensions remote url settings in vscode. `[Windows name in WSL].local` cannot be resolved inside devcontainer.

I hope you can update README and help more people using devcontainer solution like me!

**Comment by XFY9326** [comment]
Thank you for your suggestion. I have updated the README.
